ci: allow to use toolsmiths environments
Co-authored-by: Bruce Ricard <bricard@pivotal.io>

[#172191722](https://www.pivotaltracker.com/story/show/172191722)

diff --git a/ci/tasks/create-integration-configs/task b/ci/tasks/create-integration-configs/task
--- a/ci/tasks/create-integration-configs/task
+++ b/ci/tasks/create-integration-configs/task
@@ -5,10 +5,26 @@ set -eu -o pipefail
 # shellcheck disable=SC1091
 source cf-deployment-concourse-tasks/shared-functions
 
-if [[ -f networking-oss-deployments/scripts/script_helpers.sh ]]; then
-  source networking-oss-deployments/scripts/script_helpers.sh
+source networking-oss-deployments/scripts/script_helpers.sh
+
+if [[ -d toolsmiths-metadata-dir ]]; then
+  ENVIRONMENT="$(cat toolsmiths-metadata-dir/name)"
+  API_URL="$(jq -r .cf.api_url toolsmiths-metadata-dir/metadata)"
+  SYSTEM_DOMAIN="${API_URL#api.}"
+  unset API_URL
+  ADMIN_PASS="$(get_cf_admin_password_toolsmiths "${ENVIRONMENT}")"
+
+elif [[ -d networking-oss-deployments ]]; then
+  if [[ ! -n "${ENVIRONMENT}" ]]; then
+    echo 'Failed to specify "ENVIRONMENT" when using "deployments-routing"'
+    exit 1
+  fi
+  SYSTEM_DOMAIN="${ENVIRONMENT}.routing.cf-app.com"
+  ADMIN_PASS="$(extract_var "${ENVIRONMENT}" cf_admin_password)"
+
 else
-  source routing-release-ci/ci/scripts/script_helpers.sh
+  echo 'Failed to provide either "toolsmiths-metadata-dir" or "deployments-routing"'
+  exit 2
 fi
 
 mkdir -p created-integration-configs
